use Abundance6
go
select * from [onlline retail]
select distinct invoice_no, stock_code, description, quantity, invoicedate, invoicetime, unitprice, customerid, country, total from retail

1) Total of each products sold?
select sum(quantity) as total_quantity, description from [onlline retail]
group by description 
order by sum(quantity) desc


2) most bought product
select description, Max( quantity) as quantity from [onlline retail]
group by description
order by max(quantity) desc


3) least product bought
select description, min(quantity) as quantity from [onlline retail]
group by description
order by min(quantity) asc

4)Total revenue gotten from sales
select sum(total) as total_revenue from [onlline retail]

5)Total Revenue generated by each product
select description, sum(Total) as total_sales from [onlline retail]
group by description

6) Product with highest sales
select description , unitprice, quantity, total from [onlline retail]
where total = (select max(total) from [onlline retail])
order by description

7) product with the least sales
select description , unitprice, quantity, total from [onlline retail]
where total = (select min(total) from [onlline retail])
order by description

8) products with sales greater than the product with the least sales
select description, unitprice, quantity, (total) from [onlline retail]
where total >= some(select min(total) from [onlline retail]
group by description)
order by total desc

9)country that generated more revenue
select country, unitprice, quantity, total from [onlline retail]
where total = (select max(total) from [onlline retail])
order by country

10) time/day more sales took place
select invoicetime, invoicedate, unitprice, quantity, total from [onlline retail]
where total = (select max(total) from [onlline retail])
order by invoicetime

